BADGE_CHOICES = [
    ("", "None"),
    ("Foundations", "Foundations"),
    ("Practitioner", "Practitioner"),
    ("Advanced", "Advanced"),
    ("Expert", "Expert"),
    ("Coach", "Coach"),
    ("Facilitator", "Facilitator"),
    ("Program Leader", "Program Leader"),
]

LANGUAGE_NAMES = [
    "Chinese",
    "Dutch",
    "English",
    "French",
    "German",
    "Japanese",
    "Spanish",
]

MAGIC_LINK_TTL_DAYS = 30

# Default password for newly created participant accounts (non-CSA)
DEFAULT_PARTICIPANT_PASSWORD = "KTRocks!"

# Default password for newly created Client Session Administrator accounts
DEFAULT_CSA_PASSWORD = "KTRocks!CSA"

SYS_ADMIN = "app_admin"
ADMIN = "admin"
CERTIFICATE_MANAGER = "certificate_manager"
STAFF = "kt_staff"
CONTRACTOR = "kt_contractor"

ROLE_ATTRS = {
    SYS_ADMIN: "is_app_admin",
    ADMIN: "is_admin",
    "kcrm": "is_kcrm",
    CERTIFICATE_MANAGER: "is_certificate_manager",
    "kt_delivery": "is_kt_delivery",
    CONTRACTOR: "is_kt_contractor",
}

MANAGE_USERS_ROLES = {SYS_ADMIN, ADMIN}
EXCLUSIVE_ROLES = {CONTRACTOR}

ROLES_MATRIX_VERSION = "2024-10-16"

PERMISSIONS_MATRIX = {
    "columns": [
        "App_Admin",
        "is_kt_admin",
        "is_kcrm",
        "is_certificate_manager",
        "is_kt_delivery",
        "is_kt_contractor",
        "is_kt_staff",
        "Participant",
    ],
    "rows": {
        "Sessions – list & detail": {
            "App_Admin": "V C E D",
            "is_kt_admin": "V C E D",
            "is_kcrm": "V C E",
            "is_certificate_manager": "V (certificate-only)",
            "is_kt_delivery": "V (own & assigned)",
            "is_kt_contractor": "V (own & assigned)",
            "is_kt_staff": "V",
            "Participant": "V (own via My Workshops)",
        },
        "Sessions – core fields edit": {
            "App_Admin": "E",
            "is_kt_admin": "E",
            "is_kcrm": "E",
            "is_certificate_manager": "E (certificate-only)",
            "is_kt_delivery": "—",
            "is_kt_contractor": "—",
            "is_kt_staff": "—",
            "Participant": "—",
        },
        "Sessions – add participants": {
            "App_Admin": "A",
            "is_kt_admin": "A",
            "is_kcrm": "A",
            "is_certificate_manager": "A (certificate-only)",
            "is_kt_delivery": "A (own & assigned)",
            "is_kt_contractor": "A (own & assigned)",
            "is_kt_staff": "—",
            "Participant": "—",
        },
        "Sessions – finalize / cancel": {
            "App_Admin": "A",
            "is_kt_admin": "A",
            "is_kcrm": "A",
            "is_certificate_manager": "A (certificate-only)",
            "is_kt_delivery": "—",
            "is_kt_contractor": "—",
            "is_kt_staff": "—",
            "Participant": "—",
        },
        "Prework – configure (by Workshop Type)": {
            "App_Admin": "V C E D",
            "is_kt_admin": "V C E D",
            "is_kcrm": "—",
            "is_certificate_manager": "—",
            "is_kt_delivery": "—",
            "is_kt_contractor": "—",
            "is_kt_staff": "—",
            "Participant": "—",
        },
        "Prework – send / mark no-prework (by Session)": {
            "App_Admin": "A",
            "is_kt_admin": "A",
            "is_kcrm": "A",
            "is_certificate_manager": "—",
            "is_kt_delivery": "A (own & assigned)",
            "is_kt_contractor": "A (own & assigned)",
            "is_kt_staff": "—",
            "Participant": "V (complete own only)",
        },
        "Materials – create order": {
            "App_Admin": "A",
            "is_kt_admin": "A",
            "is_kcrm": "A",
            "is_certificate_manager": "—",
            "is_kt_delivery": "—",
            "is_kt_contractor": "—",
            "is_kt_staff": "—",
            "Participant": "—",
        },
        "Materials – mark ready / delivered": {
            "App_Admin": "A",
            "is_kt_admin": "A",
            "is_kcrm": "A",
            "is_certificate_manager": "—",
            "is_kt_delivery": "—",
            "is_kt_contractor": "—",
            "is_kt_staff": "—",
            "Participant": "—",
        },
        "Resources – manage (Settings → Resources)": {
            "App_Admin": "V C E D",
            "is_kt_admin": "V C E D",
            "is_kcrm": "—",
            "is_certificate_manager": "—",
            "is_kt_delivery": "—",
            "is_kt_contractor": "—",
            "is_kt_staff": "—",
            "Participant": "—",
        },
        "Resources – view (My Resources)": {
            "App_Admin": "—",
            "is_kt_admin": "—",
            "is_kcrm": "—",
            "is_certificate_manager": "—",
            "is_kt_delivery": "V",
            "is_kt_contractor": "V",
            "is_kt_staff": "—",
            "Participant": "V",
        },
        "Certificates – generate/issue": {
            "App_Admin": "A",
            "is_kt_admin": "A",
            "is_kcrm": "—",
            "is_certificate_manager": "A",
            "is_kt_delivery": "—",
            "is_kt_contractor": "—",
            "is_kt_staff": "—",
            "Participant": "V (view own)",
        },
        "Verify Certificates": {
            "App_Admin": "V",
            "is_kt_admin": "V",
            "is_kcrm": "V",
            "is_certificate_manager": "V",
            "is_kt_delivery": "V",
            "is_kt_contractor": "V",
            "is_kt_staff": "V",
            "Participant": "V",
        },
        "Workshop Types – manage": {
            "App_Admin": "V C E D",
            "is_kt_admin": "V C E D",
            "is_kcrm": "—",
            "is_certificate_manager": "—",
            "is_kt_delivery": "—",
            "is_kt_contractor": "—",
            "is_kt_staff": "—",
            "Participant": "—",
        },
        "Users – staff & learner admin (/users)": {
            "App_Admin": "V C E D",
            "is_kt_admin": "V C E D",
            "is_kcrm": "—",
            "is_certificate_manager": "—",
            "is_kt_delivery": "—",
            "is_kt_contractor": "—",
            "is_kt_staff": "—",
            "Participant": "—",
        },
        "Importer (/importer)": {
            "App_Admin": "V A",
            "is_kt_admin": "V A",
            "is_kcrm": "—",
            "is_certificate_manager": "—",
            "is_kt_delivery": "—",
            "is_kt_contractor": "—",
            "is_kt_staff": "—",
            "Participant": "—",
        },
        "Issued / Cert Form (/issued, /cert-form)": {
            "App_Admin": "V A",
            "is_kt_admin": "V A",
            "is_kcrm": "—",
            "is_certificate_manager": "V A",
            "is_kt_delivery": "—",
            "is_kt_contractor": "—",
            "is_kt_staff": "—",
            "Participant": "—",
        },
        "Settings – Roles Matrix": {
            "App_Admin": "V E",
            "is_kt_admin": "V",
            "is_kcrm": "—",
            "is_certificate_manager": "—",
            "is_kt_delivery": "—",
            "is_kt_contractor": "—",
            "is_kt_staff": "—",
            "Participant": "—",
        },
        "Settings – App/System settings": {
            "App_Admin": "V E",
            "is_kt_admin": "—",
            "is_kcrm": "—",
            "is_certificate_manager": "—",
            "is_kt_delivery": "—",
            "is_kt_contractor": "—",
            "is_kt_staff": "—",
            "Participant": "—",
        },
        "My Profile (change password, language)": {
            "App_Admin": "V E",
            "is_kt_admin": "V E",
            "is_kcrm": "V E",
            "is_certificate_manager": "V E",
            "is_kt_delivery": "V E",
            "is_kt_contractor": "V E",
            "is_kt_staff": "V E",
            "Participant": "V E",
        },
        "My Workshops / My Prework / My Certificates": {
            "App_Admin": "—",
            "is_kt_admin": "—",
            "is_kcrm": "—",
            "is_certificate_manager": "—",
            "is_kt_delivery": "V (own)",
            "is_kt_contractor": "V (own)",
            "is_kt_staff": "—",
            "Participant": "V",
        },
        "Login flows (magic links, account invites)": {
            "App_Admin": "A",
            "is_kt_admin": "A",
            "is_kcrm": "A",
            "is_certificate_manager": "—",
            "is_kt_delivery": "A (for own sessions)",
            "is_kt_contractor": "A (for own sessions)",
            "is_kt_staff": "—",
            "Participant": "—",
        },
    },
}
